version: "3"
services:
  alibaba_test:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1/80" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 60s



