version: "3"
services:
  alibaba_test:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1/80" ]
      interval: 60
      timeout: 60
      retries: 3
      start_period: 60



